#!/bin/bash

HOME_SSID=my_home_ssid
SPOOF_MAC_DIR=/usr/local/share/python
#SPOOF_MAC_DIR=/usr/local/bin

# figure out the base directory of this script
BASE_DIR=`dirname $0`
if [ ! "$BASE_DIR" = "." ]; then
cd $BASE_DIR
fi

exec &> locationchanger.log

SSID_FILE=ssid

sleep 2

AIRPORT=/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport

if [ "`$AIRPORT -I`" = "AirPort: Off" ]; then
  echo "wifi turned off"
  rm $SSID_FILE
  echo "exiting..."
  exit
fi

SSID=`$AIRPORT -I | grep ' SSID:' | cut -d ':' -f 2 | tr -d ' '`

if [ "$SSID" = "" ]; then
  echo "Too soon, no ssid set. Exiting..."
  exit
fi

if [ -e "$SSID_FILE" ]; then
  if [ "$SSID" = "`cat $SSID_FILE`" ]; then
    echo "SSID already set. Exiting..."
    exit
  fi
fi

echo "Saving '$SSID' to $SSID_FILE"
echo $SSID > $SSID_FILE

if [ "$SSID" = "$HOME_SSID" ]; then
  echo "Resetting wifi"
#  cp -f hosts-int /etc/hosts
  $SPOOF_MAC_DIR/spoof-mac reset wi-fi
else
  echo "Randomizing wifi"
#  cp -f hosts-ext /etc/hosts
  $SPOOF_MAC_DIR/spoof-mac randomize wi-fi
fi
