#!/bin/bash

HOME_SSID=my_home_ssid
SPOOF_MAC_DIR=/usr/local/share/python
#SPOOF_MAC_DIR=/usr/local/bin

# figure out the base directory of this script
BASE_DIR=`dirname $0`
if [ ! "$BASE_DIR" = "." ]; then
cd $BASE_DIR
fi

SSID_FILE=ssid

sleep 2

AIRPORT=/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport

# wifi was turned off
if [ "`$AIRPORT -I`" = "AirPort: Off" ]; then
  rm $SSID_FILE
  exit
fi

# check the current SSID we are connected to
SSID=`$AIRPORT -I | grep ' SSID:' | cut -d ':' -f 2 | tr -d ' '`

# got called too soon, we are not connected yet
if [ "$SSID" = "" ]; then
  exit
fi

# the SSID is already set. this is called a second time because of spoof-mac
if [ -e "$SSID_FILE" ]; then
  if [ "$SSID" = "`cat $SSID_FILE`" ]; then
    exit
  fi
fi

echo $SSID > $SSID_FILE

if [ "$SSID" = "$HOME_SSID" ]; then
  echo "Resetting wifi"
#  cp -f hosts-home /etc/hosts
  $SPOOF_MAC_DIR/spoof-mac reset wi-fi
else
  echo "Randomizing wifi"
#  cp -f hosts-random /etc/hosts
  $SPOOF_MAC_DIR/spoof-mac randomize wi-fi
fi

# From Apple Documentation:
# Important: If your daemon shuts down too quickly after being launched,
# launchd may think it has crashed. Daemons that continue this behavior
# may be suspended and not launched again when future requests arrive.
# To avoid this behavior, do not shut down for at least 10 seconds after launch.
sleep 10
